### ISSUE TITLE
post to GitHub

### ISSUE THREAD

**Issue by kylewm** [kylewm/silo.pub#17]
It would be nice to support publishing to GitHub. The mapping is non-trivial

- reply to a repository: post a new issue?
- reply to an issue: post a comment on that issue
- like a repository: star the repo
- repost a repository: fork the repo (just kidding, I don't think we'd want to do that)

Note that issues have titles + body, while comments only have a body.

cc @aaronpk

**Comment by aaronpk** [comment]
In my prototype of syndicating to Github, I supported the first two. I think my implementation took the first sentence of my reply and used that as the issue title.
