### ISSUE TITLE
This is a github issue without a subject, but hope…

### ISSUE THREAD

**Issue by kylewm** [kylewm/silo.pub#26]
This is a github issue without a subject, but hopefully a reasonable one will be created by truncating this text first.

**Comment by kylewm** [comment]
Test commenting on an issue...

**Comment by kylewm** [comment]
POSSEing a GitHub issue comment from my website!

**Comment by kylewm** [comment]
POSSEing a GitHub issue comment from my website! I wonder *what* happens if I include a little **markdown** in my `comment`

**Comment by aaronpk** [comment]
Testing commenting on a GitHub issue from my site via silopub
