### ISSUE TITLE
Blogger gives OAuth error

### ISSUE THREAD

**Issue by kevinmarks** [kylewm/silo.pub#33]
A google error page with

> 401. That’s an error.
> 
> Error: deleted_client
> 
> The OAuth client was deleted.
> 
> Request Details
> access_type=offline
> approval_prompt=force
> scope=https://www.googleapis.com/auth/blogger
> response_type=code
> state=1464479453##ffab36c7c6d542a54b64f64e99f1309aad62f102
> redirect_uri=https://silo.pub/blogger/callback
> client_id=838654804055-fibaineslb4k33uiiiqck65uuo64cpp9.apps.googleusercontent.com
> That’s all we know.

**Comment by kylewm** [comment]
Eek don't like the sound of that. Thanks

**Comment by kylewm** [comment]
Hopefully transient; it's working now. Please let me know if you see it again, and I will check that log!
