### ISSUE TITLE
Support photos referenced by URL

### ISSUE THREAD

**Issue by aaronpk** [kylewm/silo.pub#36]
In some cases it's tricky to build an HTTP request that includes multiple parameters with the same name (`photo[]`). In this case it would be easier for the client to put the photo at some other URL (its own public URL or upload it to some other location) and then reference the photo in the Micropub request by this URL.

**Comment by kylewm** [comment]
Could you elaborate? Why is it difficult to build a request with multiple parameters called `photo[]`

**Comment by kylewm** [comment]
Also duplicate of https://github.com/kylewm/silo.pub/issues/7 ?

**Comment by aaronpk** [comment]
Yep looks like #7 covers it.

**Comment by kylewm** [comment]
Understanding https://github.com/kylewm/silo.pub/issues/36#issuecomment-247885387 would still help :)

**Comment by aaronpk** [comment]
The problem is some HTTP libraries make you build an array (hash) of parameters to pass in the request, e.g.

```php
$params = [];
$params['photo[]'] = new CURLFile(...);
$params['photo[]'] = new CURLFile(...);
```

Obviously that won't work since they have the same key name. Of course the same problem occurs whether the value is a string or a `CURLFile` object, so I should have been more clear in my original comment. The solution to this is to make the Micropub post in JSON format and pass in the image URLs after they've been uploaded somewhere else. That way you can make a request that looks like:

```json
{
  "type": "h-entry",
  "properties": {
    "content": ["Hello World"],
    "photo": [
      "http://example.com/photo1.jpg",
      "http://example.com/photo2.jpg"
    ]
  }
}
```
