### ISSUE TITLE
Stop prepending usernames to tweet text

### ISSUE THREAD

**Issue by aaronpk** [kylewm/silo.pub#53]
Now that Twitter moved the usernames you're replying to outside of the content, it doesn't make sense for silo.pub to automatically prepend it to the content.

https://blog.twitter.com/en_us/topics/product/2017/now-on-twitter-140-characters-for-your-replies.html

I've had a few failed replies happen where my reply was truncated because silo.pub prepended the username causing me to go over the limit with the rest of the text.

**Comment by aaronpk** [comment]
Fixed in #56

**Comment by kylewm** [comment]
Thanks for the fix and sorry for the delay!!
