### ISSUE TITLE
support posting with URL of media as alternative to uploading to file data

### ISSUE THREAD

**Issue by kylewm** [kylewm/silo.pub#7]

**Comment by aaronpk** [comment]
+1!

**Comment by kylewm** [comment]
fyi @aaronpk 👍

**Comment by aaronpk** [comment]
This doesn't seem to be working, at least not with Tumblr. I'm specifying a photo URL but the post is created without the photo.

**Comment by kylewm** [comment]
Hmm, interesting, it works on my local instance, but not on silo.pub

**Comment by aaronpk** [comment]
Permissions error trying to write the temp file?

**Comment by kylewm** [comment]
It turns out the deploy had failed with some dumb python error. Recreated the virtualenv and it's good now. Sorry about that!
