### ISSUE TITLE
Provide a way to get an access token from the web interface

### ISSUE THREAD

**Issue by aaronpk** [kylewm/silo.pub#9]
It'd be awesome if I could visit a page after signing in to get an access token and see the micropub endpoint. This would make it really easy for people to use this as an alternate API for posting to silos when developing their websites.

**Comment by kylewm** [comment]
Great idea! It'll take a little bit of work (silo.pub doesn't really have a concept of "logged in" yet), but I think this would be really nice.

**Comment by aaronpk** [comment]
You could even add this without adding the "logged in" concept by just
generating a token for me after I auth the one time.

**Comment by kylewm** [comment]
Added here https://github.com/kylewm/silo.pub/commit/844b4f4ded6088cf826156a9dc37ecb4be648bcd using a secure (I think...) cookie to remember which site you most recently authed. Makes me a little nervous but it'll make testing a heck of a lot easier.

**Comment by kylewm** [comment]
Thanks for the suggestion! :+1:
